- name: Install packages for Debian-based Linux
  import_tasks: apt.yml
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install packages for Arch Linux
  import_tasks: pacman.yml
  become: yes
  when: ansible_os_family == 'Archlinux'

