# My tmux config file.
# https://tmuxcheatsheet.com


# Remove all default keybinds
unbind -a

# Set prefix to Ctrl-Space
set -g prefix C-Space
bind C-Space send-prefix

# Window navigation using prefix
bind H previous-window
bind L next-window

# Pane navigation like in Vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize split panes
bind -r Up resize-pane -U
bind -r Down resize-pane -D
bind -r Left resize-pane -L
bind -r Right resize-pane -R

# Open new split panes in cwd
bind s split-window -h -c '#{pane_current_path}'
bind v split-window -v -c '#{pane_current_path}'

# Other keybinds
bind : command-prompt
bind d detach-client
bind m show-messages
bind t clock-mode
bind q display-panes
bind z resize-pane -Z
bind b break-pane
bind x kill-pane
bind S choose-tree -w
bind w choose-window
bind W list-windows
bind p last-window
bind P last-pane
bind c new-window -c '$HOME'
bind n new-window -c '#{pane_current_path}'
bind K confirm-before -p 'kill-window #W? (y/n)' kill-window
bind r command-prompt 'rename-window %%'
bind / command-prompt -I '#S' { rename-session '%%' }
bind [ switch-client -p
bind ] switch-client -n
bind o customize-mode -Z
bind 1 select-window -t :=1
bind 2 select-window -t :=2
bind 3 select-window -t :=3
bind 4 select-window -t :=4
bind 5 select-window -t :=5

# Mouse support
set -g mouse on

# Status bar position
set -g status-position top

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on


# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-theme 'dragon'
set -g @kanagawa-plugins 'git'
set -g @kanagawa-git-disable-status false
set -g @kanagawa-git-colors 'dark_purple white'
set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-show-empty-plugins false
set -g @kanagawa-show-powerline true
set -g @kanagawa-show-flags true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
