---
core_pkgs:
  - build-essential
  - clang
  - vim
  - tmux
  - ssh
  - htop
  - atool

fun_pkgs:
  - sl
  - figlet
  - nyancat
  - cmatrix
  - neofetch
  - fortune
  - cowsay
  - lolcat
  - pacman4console

