#!/bin/bash
# This file is a place for snippets of miscellaneous code
# that are needed on the computer I'm currently using but
# are not worth putting in my other bash config files.


export NVIM_COLORSCHEME=rose-pine
