#!/bin/bash
# This file is a place for snippets of miscellaneous code
# that are needed on the computer I'm currently using but
# are not worth putting in my ~/.bashrc file.


# ghcup
export PATH="$PATH:$HOME/.cabal/bin:$HOME/.ghcup/bin"

# desktop alias
if [[ $(grep -i Microsoft /proc/version) ]]; then
    alias desktop='cd /mnt/c/users/max/desktop'
else
    alias desktop='cd ~/Desktop'
fi

