---
- name: Uninstall APT fzf
  apt:
    name: fzf
    state: absent
  become: true

- name: Check if fzf is installed
  shell: command -v fzf
  register: fzf_exists
  ignore_errors: true
  changed_when: false

- block:
  - name: Ensure fd is installed
    apt:
      name: fd-find
      state: present
    become: true

  - name: Find location of fd binary
    shell: command -v fdfind
    register: fdfind_path
    ignore_errors: true
    changed_when: false

  - name: Symlink the fd binary
    file:
      src: "{{ fdfind_path.stdout }}"
      dest: "/usr/local/bin/fd"
      owner: "{{ ansible_user_id }}"
      state: link
    become: true

  - name: Clone fzf from GitHub
    git:
      repo: https://github.com/junegunn/fzf.git
      dest: "{{ ansible_user_dir }}/.fzf"
      depth: 1
    notify: Run the fzf install script

  when: fzf_exists.failed and ansible_os_family == 'Debian'

